spring:
  application:
    name: attendance-register
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:attendance"
    username: "sa"
    password: "password"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  h2:
    console:
      enabled: true
flyway:
  url: jdbc:h2:mem:attendance
  schemas: attendance
  user: "sa"
  password: "password"

security:
  jwt:
    token:
      secret-key: javainuse
      expire-length: 300000
